version: 2
updates:
  - package-ecosystem: npm
    directory: /mobile-runtime-js
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: gradle
    directory: /android-app
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: gradle
    directory: /wire/kotlin-contract
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
